language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

sudo: false
cache: bundler

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.1.gemfile

jobs:
  exclude:
  - gemfile: gemfiles/rails_5.1.gemfile
    rvm: 2.7.1
